### ISSUE TITLE
Please update analyzer to the vesion >= 0.32.4

### ISSUE THREAD

**Issue by VladimirCores** [PureMVC/puremvc-dart-multicore-framework#5]
When I'm trying to get puremvc as dependency for Flutter project I got this message:
"Because every version of flutter_test from sdk depends on analyzer 0.32.4 and puremvc >=2.0.6 depends on analyzer ^0.10.1, flutter_test from sdk is incompatible with puremvc >=2.0.6.
So, because applied_metabolics depends on both puremvc ^2.0.6 and flutter_test any from sdk, version solving failed. "

**Comment by cliffhall** [comment]
Closing this as I see you've updated the analyzer version in your [PR](https://github.com/PureMVC/puremvc-dart-multicore-framework/pull/6).
